# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('accept_request', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Group Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InviteEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, verbose_name='Invite Emails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(max_length=20, verbose_name='Issue Type')),
                ('issue_summary', models.CharField(max_length=255, verbose_name='Issue Summary')),
                ('issue_description', models.TextField(blank=True, verbose_name='Issue Description')),
                ('issue_estimate', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('jira_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.CharField(max_length=255, verbose_name='Room id')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokerBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='PokerBoard Name')),
                ('description', models.TextField(blank=True, verbose_name='PokerBoard Description')),
                ('total_estimate', models.PositiveIntegerField(default=0, verbose_name='PokerBoard Estimate')),
                ('timer', models.PositiveIntegerField(default=0, verbose_name='PokerBoard Timer')),
                ('card_set', models.PositiveIntegerField(choices=[(1, 'Fibonacci'), (2, 'Even'), (3, 'Odd')], verbose_name='Card Set')),
                ('card_limit', models.PositiveIntegerField()),
                ('game_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Current Playing Game')),
                ('current_issue_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('custom_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.PositiveIntegerField(choices=[(1, 'Manager'), (2, 'Participant'), (3, 'Spectator')])),
                ('has_participated', models.BooleanField(default=False)),
                ('has_accepted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.CharField(max_length=255, verbose_name='Room id')),
                ('card_selected', models.PositiveIntegerField(verbose_name='Selected Card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_estimate', models.PositiveIntegerField(default=0, verbose_name='User Estimate')),
                ('response_time', models.DurationField(verbose_name='Response Time')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
