# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-13 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokerboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userestimate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercard',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Issue'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='pokerboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboard.PokerBoard'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='group_participant',
            field=models.ManyToManyField(related_name='participants', to='pokerboard.Group'),
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='group_spectator',
            field=models.ManyToManyField(related_name='spectators', to='pokerboard.Group'),
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='invite_email',
            field=models.ManyToManyField(through='pokerboard.AcceptRequest', to='pokerboard.InviteEmail'),
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='pokerboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboard.PokerBoard'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptrequest',
            name='invite_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboard.InviteEmail'),
        ),
        migrations.AddField(
            model_name='acceptrequest',
            name='pokerboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokerboard.PokerBoard'),
        ),
    ]
